apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-a
          image: ghcr.io/zplato/miniservice-service_b:latest
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: "development"
