apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: flask-app
          env:
            - name: ENV
              value: "staging"