apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
        - name: service-c
          image: ghcr.io/zplato/miniservice-service_c:latest
          ports:
            - containerPort: 5000
          env:
            - name: ENV
              value: "development"
