namespace: mesh-staging

# Include everything in here
resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patches/patch-nginx.yaml
    target:
      kind: Deployment
      name: nginx
  - path: patches/patch-flask-app.yaml
    target:
      kind: Deployment
      name: flask-app